### PR TITLE
Update systemd to v253

### LINKED ISSUE #15: Logs from Fedora 38 are not displayed
On Fedora Silverblue 38, the app only shows logs up to 2023-04-18 to the exact time when I rebooted after rebasing from F37 to F38. Any logs created on F38 are not displayed.

I see systemd is bundled in the app, so I guess it could be a matter of updating that due to compatibility with logs created by a newer version. The current Fedora package is `systemd-253.2-1.fc38.x86_64`, while this app is at v251.

### PR DESCRIPTION
**Pull request by jntesteves**
Resolves #15

### CODE REVIEW

**Comment by A6GibKm** [comment]
Did you test this?

**Comment by jntesteves** [comment]
> Did you test this?

I previously tested building locally. Haven't tested the CI build yet.

**Comment by jntesteves** [comment]
Just installed the CI build, everything working fine here.

**Comment by A6GibKm** [comment]
Thanks!

**Pull request merged**
